### PR TITLE
Flash issue

### PR DESCRIPTION
**Pull request by kingdomcoding**

### CODE REVIEW

**Comment by kingdomcoding** [comment]
I can't get the phx-disconnect flash displayed.

Did you deliberately prevent that from happening?

I noticed some attributes are different between `CoreComponents` and `Pyro.Components.Core`. Is that also deliberate?

**Review by frankdugan3 — COMMENTED** [review]
This is intentionally a string as that is how it is actually stored:

https://github.com/phoenixframework/phoenix/blob/v1.7.0-rc.2/lib/phoenix/flash.ex#LL25C35-L25C35

**Comment by frankdugan3** [comment]
> I noticed some attributes are different between CoreComponents and Pyro.Components.Core. Is that also deliberate?

I may have added some options, but if there are any breaking attributes, that is unintentional. Can you be more specific?

**Comment by frankdugan3** [comment]
> I can't get the phx-disconnect flash displayed.
> Did you deliberately prevent that from happening?

That was just an oversight in my implementation. Can you create a separate issue for that?

**Pull request closed without merging**
